---
title: "Milestone 3: Data Cleaning"
author: "Debi Gonzalez"
date: "April 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(gt)
```

```{r Data Download, echo = FALSE}
data1 <- read_excel("Voter_Registration_By_County_and_Party_Feb_2019.xlsx")
# Data1 is a spreadsheet containing voter registration of FL voters by county and party as of Feb. 2019.
data2 <- read_excel("Voter_Registration_By_Party_Affiliation_Feb_2019.xlsx")
# Data2 is a spreadsheet containing voter registration of FL voters by party as of Feb. 2019 from 1972 to 2019.

```


## A Glimpse at the Data
```{r Table, echo = FALSE}

data1 %>%
  drop_na() %>% 
  gt() %>% 
  tab_header("Florida's Voter Registration By County & Party 2019") %>% 
  tab_source_note("Source: Florida Department of State - Division of Elections Voter Registration Data")


```

## FL Counties with Most Registered Republicans
```{r Test Graphic, echo = FALSE}

data1 %>% 
  select(County, `Republican Party Of Florida`) %>%
  filter(County != "TOTALS") %>% 
  arrange(desc(`Republican Party Of Florida`)) %>% 
  slice(1:5) %>% 
  ggplot(aes(x = County,  y = `Republican Party Of Florida`)) +
  geom_point() +
  labs(title = "Florida's Most Republican Counties",
       subtitle = "Florida counties with the highest number of registered Republicans as of 2019",
       caption = "Source: Florida Department of State - Division of Elections Voter Registration Data")

# Need to work on data to make sure it's graphable. All numbers are as dbl and county as chr.
```

