---
title: "Milestone 3: Data Cleaning"
author: "Debi Gonzalez"
date: "April 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(gt)
library(tigris)
library(janitor)
```

```{r Data Download, echo = FALSE}
data1 <- read_excel("Voter_Registration_By_County_and_Party_Feb_2019.xlsx")

# Data1 is a spreadsheet containing voter registration of FL voters by county
# and party as of Feb. 2019.


data2 <- read_excel("Voter_Registration_By_Party_Affiliation_Feb_2019.xlsx")

# Data2 is a spreadsheet containing voter registration of FL voters by party as
# of Feb. 2019 from 1972 to 2019.


latino_types <- read_csv("Bureau_Downloads/Types_of_Latinos_in_FL_2010/DEC_10_SF1_QTP10_with_ann.csv", skip = 1)
latino_types <- latino_types[, ! str_detect(names(latino_types), pattern = "Margin of Error")] %>% 
  clean_names()

# This data shows the number and percent of latinos by country in FL.


data3 %>% 
  separate(number_hispanic_or_latino_by_type_hispanic_or_latino_of_any_race_central_american_excludes_mexican = c("number", "country"), convert = TRUE)

  # gather(str_detect(``, key = "", value = "number")



foreign_native <- read_csv("Bureau_Downloads/Characteristics_of_Native_and_Foreign-born_Populations/ACS_17_5YR_S0501_with_ann.csv", skip = 1)
data4 <- foreign_native[, ! str_detect(names(foreign_native), pattern = "Margin of Error")]

# This data shows the age, gender, nativity/naturalization status of individuals
# in FL.


language_home <- read_csv("Bureau_Downloads/CHARACTERISTICS_OF_PEOPLE_BY_LANGUAGE_SPOKEN_AT_HOME/ACS_17_5YR_Lang_spoken_with_ann.csv", skip = 1)
data5 <- language_home[, ! str_detect(names(language_home), pattern = "Margin of Error")]

# This language shows characteristics of people (age, gender, etc.) by the
# language they speak at home.


foreign_pop_county <- read_csv("Bureau_Downloads/PERCENT_OF_PEOPLE_WHO_ARE_FOREIGN_BORN_State_By_County 2013-2017/ACS_17_5YR_GCT0501.ST05_with_ann.csv", skip = 1) 
data6 <- foreign_pop_county[, ! str_detect(names(foreign_pop_county), pattern = "Margin of Error")]

# This data shows the percent of foreign born individuals by county. READY FOR USE


income_county <- read_csv("Bureau_Downloads/MEDIAN_FAMILY_INCOME/ACS_17_5YR_GCT1902.ST05_with_ann.csv", skip = 1)
data7 <- income_county[, ! str_detect(names(income_county), pattern = "Margin of Error")]

# Median family income by county. READY FOR USE.


occupation <- read_csv("Bureau_Downloads/OCCUPATION_BY_SEX_FOR_THE_CIVILIAN_EMPLOYED_POPULATION_16_YEARS_AND_OVER/ACS_17_5YR_S2401_with_ann.csv", skip = 1)
data8 <- occupation[, ! str_detect(names(occupation), pattern = "Margin of Error")]

# Occupation by sex - percent and number

#I downloaded a series of csv files from the US Census Bureau, but the files downloaded as .zip files, however, it seems like the data is distorted. Can you guys help me figure out how to fix these files in order to load them in? Thank you in advance.

# gather can be used to fix some of them.

```


## A Glimpse at the Data
```{r Table, echo = FALSE}

data1 %>%
  drop_na() %>% 
  gt() %>% 
  tab_header("Florida's Voter Registration By County & Party 2019") %>% 
  tab_source_note("Source: Florida Department of State - Division of Elections Voter Registration Data")

```

## FL Counties with Most Registered Republicans
```{r Test Graphic, echo = FALSE}

data1 %>% 
  #select(County, `Republican Party Of Florida`) %>%
  filter(County != "TOTALS") %>% 
  arrange(desc(`Republican Party Of Florida`)) %>% 
  slice(1:5) %>% 
  ggplot(aes(x = County,  y = `Florida Democratic Party`)) +
  geom_bar(stat = "identity") +
  labs(title = "Florida's Most Republican Counties",
       subtitle = "Florida counties with the highest number of registered Republicans as of 2019",
       caption = "Source: Florida Department of State - Division of Elections Voter Registration Data")

# Need to work on data to make sure it's graphable. All numbers are as dbl and county as chr.
# Look at Healy on bar charts
# See if maps are possible

# check how to change y labels to not scientific notation
```


```{r}

data_2017 <- read_csv(file = "2017_data.csv", skip = 1)
census_2017_nomargin <- data_2017[, ! str_detect(names(data_2017), pattern = "Margin of Error")]
```

